### ISSUE TITLE
Make sure git storage is correct

### ISSUE THREAD

**Issue by jkiske** [benperez/engine-import-test#26]
```
spec:...
  volumeClaimTemplates:
    - metadata:
        name: git-root-{{org-name}}
  ...
  volumeClaimTemplates:
        volumeMounts:
          - name: git-root-{{org-name}}
            mountPath: "/home/git"
```
